import { cookieStorage, createStorage, Storage } from '@wagmi/core';
import { WagmiAdapter } from '@reown/appkit-adapter-wagmi';
import { mainnet, arbitrum, AppKitNetwork } from '@reown/appkit/networks';

// Read Project ID from environment variables
export const projectId = import.meta.env.VITE_PROJECT_ID;

// Ensure Project ID is defined at build time
if (!projectId) {
  throw new Error('VITE_PROJECT_ID is not defined. Please set it in .env');
}

// Define supported networks
export const networks: [AppKitNetwork, ...AppKitNetwork[]] = [
  mainnet,
  arbitrum,
];
const storage: Storage = createStorage({ storage: cookieStorage });

// Create the Wagmi adapter instance
export const wagmiAdapter = new WagmiAdapter({
  storage,
  ssr: true,
  projectId,
  networks,
});

// Export the Wagmi config generated by the adapter
export const config = wagmiAdapter.wagmiConfig;
