import { WagmiAdapter } from '@reown/appkit-adapter-wagmi'

import { networks } from './appkit'

// Read Project ID from environment variables
const projectId = import.meta.env.VITE_PROJECT_ID

if (!projectId) {
  throw new Error('VITE_PROJECT_ID is required')
}

// Create the Wagmi adapter instance
export const wagmiAdapter = new WagmiAdapter({
  projectId,
  networks,
})

// Export the Wagmi config generated by the adapter
export const wagmiConfig = wagmiAdapter.wagmiConfig
