import { WagmiAdapter } from '@reown/appkit-adapter-wagmi';
import { createStorage, cookieStorage } from 'wagmi';
import { networks } from './appkit';

// Read Project ID from environment variables
export const projectId = import.meta.env.VITE_PROJECT_ID;

const storage = createStorage({ storage: cookieStorage });

// Create the Wagmi adapter instance
export const wagmiAdapter = new WagmiAdapter({
  storage,
  ssr: true,
  projectId,
  networks,
});

// Export the Wagmi config generated by the adapter
export const wagmiConfig = wagmiAdapter.wagmiConfig;
