#!/usr/bin/env bun

import fs from 'fs/promises'
import path from 'path'

interface RddEntry {
  name: string
  proxyAddress: string
  decimals: number
  feedType: string
  docs?: {
    assetClass?: string
    baseAsset?: string
    quoteAsset?: string
    productType?: string
    hidden?: boolean
  }
}

const RDD_URLS: Record<number, string> = {
  1: 'https://reference-data-directory.vercel.app/feeds-mainnet.json',
  42161: 'https://reference-data-directory.vercel.app/feeds-ethereum-mainnet-arbitrum-1.json',
  100: 'https://reference-data-directory.vercel.app/feeds-xdai-mainnet.json',
}

const ZERO_ADDRESS = '0x0000000000000000000000000000000000000000'

const SYMBOL_ALIASES: Record<string, string[]> = {
  ETH: ['WETH'],
  BTC: ['WBTC'],
}

interface ChainlinkFeed {
  address: string
  decimals: number
}

async function fetchRddFeeds(url: string): Promise<Record<string, ChainlinkFeed>> {
  const response = await fetch(url)
  if (!response.ok) {
    throw new Error(`HTTP ${response.status}: ${response.statusText}`)
  }
  const entries: RddEntry[] = await response.json()
  const feeds: Record<string, ChainlinkFeed> = {}

  for (const entry of entries) {
    if (entry.docs?.quoteAsset !== 'USD') continue
    if (entry.docs?.assetClass !== 'Crypto') continue
    if (entry.docs?.productType !== 'Price') continue
    if (entry.docs?.hidden) continue
    if (!entry.proxyAddress || entry.proxyAddress === ZERO_ADDRESS || entry.proxyAddress === 'null') continue
    if (entry.name.includes('SVR')) continue

    const symbol = entry.docs.baseAsset?.toUpperCase()
    if (!symbol) continue

    // First match wins — verified feeds are listed first in RDD
    if (feeds[symbol]) continue

    feeds[symbol] = { address: entry.proxyAddress, decimals: entry.decimals }

    const aliases = SYMBOL_ALIASES[symbol]
    if (aliases) {
      for (const alias of aliases) {
        if (!feeds[alias]) feeds[alias] = feeds[symbol]
      }
    }
  }

  return feeds
}

async function main() {
  console.log('=== Updating Chainlink Price Feeds ===\n')

  const allFeeds: Record<number, Record<string, ChainlinkFeed>> = {}

  const results = await Promise.all(
    Object.entries(RDD_URLS).map(async ([chainIdStr, url]) => {
      const chainId = Number(chainIdStr)
      console.log(`Fetching chain ${chainId}...`)
      const feeds = await fetchRddFeeds(url)
      console.log(`  ${Object.keys(feeds).length} feeds`)
      return [chainId, feeds] as const
    })
  )

  for (const [chainId, feeds] of results) {
    allFeeds[chainId] = feeds
  }

  const outputPath = path.join(
    __dirname,
    '../apps/agentic-server/src/lib/composableCow/generated/chainlinkFeeds.ts'
  )

  const lines: string[] = [
    '// Do not edit — generated by `bun run update-oracles`',
    "import type { ChainlinkFeed } from '../oracles'",
    '',
    'export const GENERATED_ORACLES: Record<number, Record<string, ChainlinkFeed>> = {',
  ]

  for (const [chainId, feeds] of Object.entries(allFeeds).sort(
    ([a], [b]) => Number(a) - Number(b)
  )) {
    lines.push(`  ${chainId}: {`)
    for (const [symbol, feed] of Object.entries(feeds).sort(([a], [b]) => a.localeCompare(b))) {
      lines.push(`    ${JSON.stringify(symbol)}: { address: '${feed.address}', decimals: ${feed.decimals} },`)
    }
    lines.push('  },')
  }

  lines.push('}')
  lines.push('')

  await fs.writeFile(outputPath, lines.join('\n'), 'utf-8')

  const totalFeeds = Object.values(allFeeds).reduce((sum, feeds) => sum + Object.keys(feeds).length, 0)
  console.log(`\nWrote ${totalFeeds} feeds across ${Object.keys(allFeeds).length} chains to:`)
  console.log(`  ${outputPath}\n`)
}

main().catch(err => {
  console.error('\nFailed:', err)
  process.exit(1)
})
