name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - uses: actions/cache@v4
        with:
          path: .eslintcache
          key: eslint-${{ hashFiles('eslint.config.ts') }}
          restore-keys: eslint-

      - run: bun install --frozen-lockfile
      - run: bun build
      - run: bun concurrently --kill-others-on-fail "bun type-check" "bun lint" "bun test"
